[Environment]Module Types;

(* These values are returned by the predefined STATUS function. *)

    PAS$K_EOF        = -1;      (* file is at end-of-file *)
    PAS$K_SUCCESS    =  0;      (* last operation successful *)

    PAS$K_FILAROPE   =  1;      (* file is already open *)
    PAS$K_ERRDUROPE  =  2;      (* error during OPEN *)
    PAS$K_FILNOTFOU  =  3;      (* file not found *)
    PAS$K_INVFILSYN  =  4;      (* invalid filename syntax *)
    PAS$K_ACCMETINC  =  5;      (* ACCESS_METHOD specified is incompatible with this file *)
    PAS$K_RECLENINC  =  6;      (* RECORD_LENGTH specified is inconsistent with this file *)
    PAS$K_RECTYPINC  =  7;      (* RECORD_TYPE specified is inconsistent with this file *)
    PAS$K_ORGSPEINC  =  8;      (* ORGANIZATION specified is inconsistent with this file *)
    PAS$K_INVKEYDEF  =  9;      (* invalid key definition *)
    PAS$K_KEYDEFINC  = 10;      (* KEY(<n>) definition is inconsistent with this file. *)
    PAS$K_KEYNOTDEF  = 11;      (* KEY(<n>) definition is not defined in this file. *)
    PAS$K_INVRECLEN  = 12;      (* invalid record length of <n> *)
    PAS$K_TEXREGSEG  = 13;      (* textfiles require sequential organization and access *)
    PAS$K_FILENAMREG = 14;      (* FILE_NAME required for this HISTORY or DISPOSITION *)
    PAS$K_FILALRCLO  = 15;      (* file is already closed *)
    PAS$K_ERRDURCLO  = 16;      (* error during CLOSE *)
    PAS$K_AMBVALENU  = 30;      (* "<string>" is an ambiguous value for enumerated type "<type>" *)
    PAS$K_INVSYNENU  = 31;      (* "<string>" is invalid syntax for an enumerated value *)
    PAS$K_INVSYNINT  = 32;      (* "<string>" is invalid syntax for an integer value *)
    PAS$K_INVSYNREA  = 33;      (* "<string>" is invalid syntax for a real value *)
    PAS$K_INVSYNUNS  = 34;      (* "<string>" is invalid syntax for an unsigned value *)
    PAS$K_NOTVALTYP  = 35;      (* "<string>" is not a value of type "<type>" *)
    PAS$K_ERRDURPRO  = 36;      (* error during prompting *)
    PAS$K_INVSYNBIN  = 37;      (* "<string>" is invalid syntax for a binary value *)
    PAS$K_INVSYNHEX  = 38;      (* "<string>" is invalid syntax for a hexadecimal value *)
    PAS$K_INVSYNOCT  = 39;      (* "<string>" is invalid syntax for an octal value *)

    PAS$K_ERRDURWRI  = 50;      (* error during WRITELN *)
    PAS$K_INVFIESPE  = 51;      (* invalid field specification for WRITE *)
    PAS$K_LINTOOLON  = 52;      (* line is too long, exceeded record length by <n> character(s) *)
    PAS$K_NEGWIDDIG  = 53;      (* negative Width or Digits specification is not allowed *)
